Achievements:
  - src/achievements.hpp
  - src/achievements.cpp
  - src/gui/dialogs/achievements_dialog.hpp
  - src/gui/dialogs/achievements_dialog.cpp
  - data/achievements.cfg
  - data/campaigns/Dead_Water/achievements.cfg
  - data/campaigns/Delfadors_Memoirs/achievements.cfg
  - data/campaigns/Descent_Into_Darkness/achievements.cfg
  - data/campaigns/Eastern_Invasion/achievements.cfg
  - data/campaigns/Heir_To_The_Throne/achievements.cfg
  - data/campaigns/Legend_of_Wesmere/achievements.cfg
  - data/campaigns/Liberty/achievements.cfg
  - data/campaigns/Northern_Rebirth/achievements.cfg
  - data/campaigns/Sceptre_of_Fire/achievements.cfg
  - data/campaigns/Secrets_of_the_Ancients/achievements.cfg
  - data/campaigns/Son_Of_The_Black_Eye/achievements.cfg
  - data/campaigns/The_Hammer_of_Thursagan/achievements.cfg
  - data/campaigns/The_Rise_Of_Wesnoth/achievements.cfg
  - data/campaigns/The_South_Guard/achievements.cfg
  - data/campaigns/tutorial/achievements.cfg
  - data/campaigns/Two_Brothers/achievements.cfg
  - data/campaigns/Under_the_Burning_Suns/achievements.cfg
  - data/campaigns/Winds_of_Fate/achievements.cfg
  - data/campaigns/World_Conquest/achievements.cfg

Add-ons:
  - src/server/campaignd/**
  - src/server/common/**
  - src/addon/**
  - src/gui/dialogs/addon/**

AI:
  - data/ai/**/*
  - data/campaigns/*/ai/**
  - src/ai/**/*

Audio:
  - data/campaigns/*/sounds/**
  - data/core/music/*
  - data/core/sounds/**/*
  - sounds/*

Building:
  - projectfiles/**/*
  - source_lists/*
  - CMakeLists.txt
  - cmake/*
  - src/CMakeLists.txt
  - SConstruct
  - scons/*
  - src/SConscript
  - src/SConstruct

Campaign:
  - data/campaigns/**/*

CMake:
  - CMakeLists.txt
  - cmake/*
  - src/CMakeLists.txt

Docker:
  - .dockerignore
  - utils/dockerbuilds/travis/*
  - utils/travis/docker_run.sh

Docs:
  - doc/**/*

Editor:
  - data/core/editor/*
  - src/editor/**/*

Graphics:
  - images/**/*
  - data/campaigns/*/images/**
  - data/core/images/**/*

Help:
  - data/tips.cfg
  - data/core/help.cfg
  - src/help/*
  - src/gui/dialogs/help_browser.*

Input:
  - data/core/hotkeys.cfg

Lua API:
  - src/scripting/**/*
  - data/lua/**/*

macOS:
  - projectfiles/Xcode/**/*
  - src/macosx/*

MP:
  - data/multiplayer/**/*
  - src/server/wesnothd/**
  - src/server/common/**

Packaging:
  - packaging/**/*

Schema:
  - utils/travis/schema_validation.sh
  - data/schema/**/*
  - src/serialization/schema/*

SCons:
  - SConstruct
  - scons/*
  - src/SConscript
  - src/SConstruct

Services:
  - utils/mp-server/**

Terrain:
  - src/terrain/**/*
  - data/campaigns/*/images/terrain/**
  - data/campaigns/**/terrain.cfg
  - data/campaigns/**/terrain_graphics.cfg
  - data/core/images/terrain/**
  - data/core/terrain.cfg
  - data/core/terrain-graphics.cfg
  - data/core/terrain-graphics/**

Translations:
  - po/**/*
  - data/languages/*

Travis:
  - utils/travis/**/*

UI:
  - src/gui/**/*
  - data/gui/**/*
  - data/schema/gui.cfg
  - data/themes/*

Unit Tests:
  - data/test/**/*

Units:
  - src/units/**/*
  - data/campaigns/*/units/**
  - data/core/units/**/*
  - data/core/images/units/**/*

WML Tools:
  - data/tools/**/*

WFL:
  - src/formula/**
  - src/ai/formula/**
