name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux-01:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: Ubuntu 20.04 - scons, gcc, LTO, unit tests
        run: |
          ./.github/workflows/ci-scripts/ubuntu.sh
